### ISSUE TITLE
Imported SVG being omitted on final CSS

### ISSUE THREAD

**Issue by hmaesta** [ls-age/svelte-preprocess-sass#101]
```svelte
<script>
    import IconClose from './Icon_Close.svg'; 
</script>

{@html IconClose}

<style lang="scss">
 svg {
   path {
     fill: yellow;
   }
 }
</style>
```

I believe that's related to something trying to let the code smaller (_"since the SVG is not on this file, this class shouldn't be on the CSS"_).

**Comment by LukasHechenberger** [comment]
Well, The styles get eliminated, because no <svg /> tag is present in the component’s markup. Why not use <svg src=“./Icon.svg” />?

**Comment by LukasHechenberger** [comment]
Anyway, this is not related to the way this plugin handles styles, it should be the same for regular CSS, so I'll close this as not related. If my suggestion doesn't fix your problem, reopen this discussion in the svelte repo.

**Comment by hmaesta** [comment]
Hey Lukas. Thank you for the fast response. 

Indeed this is not related to this plugin – I thought so because in another project I use Sass with Svelte and this not occurs, but I realised that the SCSS is build separately.

Anyway, just for future reference, that's how to fix it:

```css
:global(svg) {
   :global(path) {
      fill: yellow;
   }
}
```

_Ps: for this particular case I ended adding `fill='currentColor'` on all SVGs and adding the color to SVG parent element to avoid this kind of "official workaround" from Svelte._

**Comment by LukasHechenberger** [comment]
This should also work, and does not pollute the global styles:

```svelte
<style>
  .icon :global(path) {
    fill: yellow;
  }
</style>

<svg class="icon" src=“./Icon.svg” />
```

**Comment by LukasHechenberger** [comment]
And thanks for sharing 😀

**Comment by hmaesta** [comment]
`<svg src="./Icon.svg"/>` doesn't work for me.

I am using [rollup-plugin-svg-import](https://github.com/bravecow/rollup-plugin-svg-import), so I have to import the file and then `{@html icon}`

Are you using another importing method?

**Comment by LukasHechenberger** [comment]
Oh, I see, you import it as a string. In most cases, I do not inline SVG icons as they're usually used in multiple components...

In this case, wrap it in a div to prevent global style pollution:

```svelte
<script>
    import IconClose from './Icon_Close.svg'; 
</script>

<style>
 .icon :global(path) {
   fill: yellow;
 }
</style>

<div class="icon">
  {@html IconClose}
</div>
```
