### ISSUE TITLE
Move from `node-sass` to `sass`

### ISSUE THREAD

**Issue by EMH333** [ls-age/svelte-preprocess-sass#112]
One of the biggest things I noticed when using this preprocessor is the required installation of `node-sass`. node-sass is deprecated (see [README](https://www.npmjs.com/package/node-sass)) and brings in a ton of dependencies (if I remember it added 100+ to one of my projects, many outdated) that cause unneeded bloat for a simple project. Additionally it requires native libraries which is less appealing for CI or other systems.

The npm [`sass`](https://www.npmjs.com/package/sass) package is officially recommended by the SASS team and is compiled from the Dart version meaning it tends to get updates quicker. Additionally it has the same API so it should just be a drop-in replacement. Performance also is fairly nominal.

I'd be happy to take a swing at replacing it or could also support either of them so the end user gets to decide.

Thanks!

**Comment by EMH333** [comment]
@LukasHechenberger Thoughts?

**Comment by LukasHechenberger** [comment]
Yeah, i already noticed, I'll patch it as soon as possible. Thanks for reminding and sorry for the delay.

**Comment by LukasHechenberger** [comment]
Released in v2.0.0 🎉 Thanks for contributing!
