### ISSUE TITLE
Setup With Webpack

### ISSUE THREAD

**Issue by s0kil** [ls-age/svelte-preprocess-sass#3]
Is it ideal to use this with webpack? Will it work?

**Comment by LukasHechenberger** [comment]
Yes, I'm actually using it in a Sapper project.
The only difference when using the svelte-loader is, that you'll have to pass the preprocessor directly instead of inside a `preprocess` attribute:

```javascript
// usage with rollup or svelte directly
svelte({
  dev,
  preprocess: {
    style: sass(),
  }
}),
```

should be

```javascript
// usage with webpack
...
use: {
  loader: 'svelte-loader',
  options: {
   // other options, like hydratable, store, ...
    style: sass(),
  }
}
```

**Comment by LukasHechenberger** [comment]
This was fixed meanwhile. You can now use it like:

```javascript
...
use: {
  loader: 'svelte-loader',
  options: {
    // other options, like hydratable, store, ...
    preprocess: {
      style: sass(),
    },
  },
},
```

**Comment by benjamin-hull** [comment]
Apologies for dredging this up - I'm new to this whole webpacker thing, and get the feeling I'm missing something crucial.

I'm trying to make this work with rails/webpacker, and have svelte itself running and happy. I have this in `config/webpack/environment.js`:

```
const { environment } = require('@rails/webpacker')
const sass = require('svelte-preprocess-sass')
const svelte =  require('./loaders/svelte')

environment.loaders.prepend('svelte', svelte)

module.exports = environment

```
and this in `config/webpack/loaders/svelte.js`:

```
module.exports = {
  test: /\.svelte$/,
  use: [{
    loader: 'svelte-loader',
    options: {
      hotReload: true,
      preprocess: {
        style: sass()
      }
    }
  }]
}
```

This fails on compilation with "ReferenceError: sass is not defined"

Without the preprocess entry and the sass require, everything works. I suspect I'm not understanding how the require portion of webpacker works properly - if anyone can point me in the right direction it'd be much appreciated!

**Comment by LukasHechenberger** [comment]
Well, I guess you just have to move the `const sass ...` to your svelte.js file

**Comment by benjamin-hull** [comment]
That helped, thanks @LukasHechenberger . I'm still wrangling with getting the indentedSyntax to work, but I'll hopefully be able to straighten that out. Cheers.
