### ISSUE TITLE
Using the indented syntax option doesn't seem to work with Svelte's global selectors.

### ISSUE THREAD

**Issue by elliotwaite** [ls-age/svelte-preprocess-sass#49]
When I try to use Sass's indented syntax option with one of Svelte's global selectors, I get an error.

rollup.config.js (using Sapper):
```
import { sass } from "svelte-preprocess-sass";

const sassOptions = {
  indentedSyntax: true
}

// Client:
svelte({
        dev,
        hydratable: true,
        emitCss: true,
        preprocess: {
          style: sass(sassOptions)
        }
}),

// Server
svelte({
        generate: "ssr",
        dev,
        preprocess: {
          style: sass(sassOptions)
        }
}),
```

component.svelte
```
<style type="text/sass">
:global(body)
  background: red
</style>
```

When I call `npm run dev` I get this error:
```
✗ server
Invalid CSS after "": expected 1 selector or at-rule, was "global(body): {"
✗ client
Invalid CSS after "": expected 1 selector or at-rule, was "global(body): {"
```

Any suggestions?

**Comment by LukasHechenberger** [comment]
Took some time to find this one 😄

The problem is, that [it's invalid sass](https://gist.github.com/LukasHechenberger/2e46c6ffbca1cd44af1ed8f6faba3852)... There's nothing I can do about it, I'd advise you to write scss instead. You could also create an issue in the svelte repo.

**Comment by elliotwaite** [comment]
Yeah, was hoping there might be some way to make this plugin recognize the Svelte `:global(...)` selector and do something special to make it work, but perhaps there will be a better way to get it to work.

One idea I'm trying to get to work is just using scss for

**Comment by LukasHechenberger** [comment]
Well, only one `<style>` element is supported in svelte, so I guess you'll have to use scss anyway...

But you actually stumbled over an issue in `rollup-preprocess-svelte`, where multiple preprocessors are currently not supported. I fixed this one, and created a corresponding [PR](https://github.com/rollup/rollup-plugin-svelte/pull/57). Once this one is merged you'll get the right error message:

```
$ npx rollup -c
index.js → public/bundle.js...
[!] (svelte plugin) ParseError: You can only have one top-level <style> tag per component
App.svelte
3: </style>
4: 
5: <style type="text/scss">
   ^
6: :global(h1) {
7:   background: red;
ParseError: You can only have one top-level <style> tag per component
    at error$1 (/Users/lukas/Downloads/gi2el/node_modules/svelte/compiler.js:13494:20)
    at Parser$2.error (/Users/lukas/Downloads/gi2el/node_modules/svelte/compiler.js:13570:10)
    at parse$2 (/Users/lukas/Downloads/gi2el/node_modules/svelte/compiler.js:13664:17)
    at compile (/Users/lukas/Downloads/gi2el/node_modules/svelte/compiler.js:23813:12)
    at preprocessPromise.then.code (/Users/lukas/Downloads/gi2el/node_modules/rollup-plugin-svelte/index.js:259:22) 
```

**Comment by elliotwaite** [comment]
Ah, got it. Didn't know about the single `<style>` limitation. Thanks for pointing that out.

I was wondering why adding multiple preprocessors seemed to give strange results. But yeah, looks like that PR or the other one should fix it. 👍

Thanks for the help.

**Comment by elliotwaite** [comment]
Just found a solution! Adding the backslash escape character `\:global(...)` makes it valid indented sass syntax.
```
<style type="text/sass">
\:global(body)
  background: red
</style>
```
Thanks again for helping me with this.
