### ISSUE TITLE
Clarify how to use with scss

### ISSUE THREAD

**Issue by yackSpillsaps** [ls-age/svelte-preprocess-sass#58]
The README says to set the "name" option to "scss".  It's not clear which options object it's referring to.

Context: I'm using with Webpack. It seems to work fine with scss if the enclosing style tag in a Svelte component has `lang="sass"`, but I cannot figure out how to configure this preprocessor to work on scss inside tags that are correctly attributed with `lang="scss"`.

**Comment by cyderize** [comment]
I believe you put it in the second argument to `sass`:
```js
sass(
  {} // Empty sass options
  { name: 'scss' } // Allow lang="scss"
)
```

**Comment by LukasHechenberger** [comment]
That's right. I'll update the readme...
