### ISSUE TITLE
How to use it with other preprocessors?

### ISSUE THREAD

**Issue by JCKodel** [ls-age/svelte-preprocess-sass#90]
I'm currently using `@pyoner/svelte-ts-preprocess` and can't figure out how to merge both preprocessors.

Tried `preprocess: [preprocess(opts), sass({}, { name: "scss" })]` without success.

**Comment by LukasHechenberger** [comment]
In which context? Are you using svelte compiler API, rollup, webpack, ... ?

In general, just pass an array of `{ markup, script, style }` objects instead of a single one.

[Svelte docs](https://svelte.dev/docs#svelte_preprocess)

**with svelte compiler** (more or less from the docs above)
```javascript
import svelte from 'svelte/compiler';
import { sass } from 'svelte-preprocess-sass';

const { code } = svelte.preprocess(source, [
	{
		// Add other preprocessors here
		markup: () => {
			console.log('this runs first');
		},
		script: () => {
			console.log('this runs third');
		},
		style: () => {
			console.log('this runs fifth');
		}
	},
	{
		style: sass({}, { name: 'scss' })
	}
], {
	filename: 'App.svelte'
});
```

**Comment by LukasHechenberger** [comment]
In your case, as the *@pyoner/svelte-ts-preprocess* already returns such an object:

```javascript
import svelte from 'svelte/compiler';
import { preprocess } from '@pyoner/svelte-ts-preprocess';
import { sass } from 'svelte-preprocess-sass';

const { code } = svelte.preprocess(source, [
	preprocess(),
	{
		style: sass({}, { name: 'scss' })
	}
], {
	filename: 'App.svelte'
});
```

**Comment by LukasHechenberger** [comment]
(untested 😁)

**Comment by JCKodel** [comment]
This works, for compilation (the second one, with []). 

The problem lies with svelte.config.js (as it is required for VSCode to work properly).

**Comment by LukasHechenberger** [comment]
Okay, don't really know what problem you mean ^^ But I assume it's not a problem with this package, so I'll close this issue. Feel free to reopen it for further discussion.
