### ISSUE TITLE
Alias path resolving possible?

### ISSUE THREAD

**Issue by rottmann** [ls-age/svelte-preprocess-sass#91]
With @rollup/plugin-alias you can replace paths, but this will not affect import paths within style.

e.g. you have a main.scss file in the root dir and you want to import it into the component

/root/components/some-component/some-componen.svelte
```
<style lang="sass">
  @import "../../main.scss";
</style>
```

with alias usage it could look like this:
```
<style lang="sass">
  @import "~/main.scss";
</style>
```

**Comment by LukasHechenberger** [comment]
The resolution of `@import` statements is handled by node-sass, so the plugin cannot work in this case. Why not just add the root directory as an *includePath*?

```javascript
...
sass({
  includePaths: ['root']
})
```

This way you don't even need the `~` and can instead write `@import 'main.scss'`...

**Comment by rottmann** [comment]
Thanks, that would be ok too.

**Comment by pavelsokolov21** [comment]
Hi both! I've another issue. I've added this configuration to my rollup config:
![image](https://user-images.githubusercontent.com/49731235/163676983-e05e03b7-afbe-49f2-afe8-321026bf7699.png)

And I see the following issue when I imported my file:
![image](https://user-images.githubusercontent.com/49731235/163676962-6aeaf890-e7d5-4514-82ed-465db48edeb8.png)

But I don't see any errors in the console:
![image](https://user-images.githubusercontent.com/49731235/163677064-d3e589e5-add7-4746-97e0-ee97f270315c.png)

**Comment by pavelsokolov21** [comment]
The quick answer:
I've just added the following code and the error is gone away
![image](https://user-images.githubusercontent.com/49731235/163677194-f26ebc54-9d82-4c99-834f-6e6a52af404f.png)

**Comment by LukasHechenberger** [comment]
I think if you include "src/styles" you can @import it as "variables.scss". Otherwise use "src" as your include path.
