### ISSUE TITLE
Top-level selectors getting svelte-token appended twice

### ISSUE THREAD

**Issue by dnmurray** [ls-age/svelte-preprocess-sass#93]
I just started playing with svelte and am trying to incorporate sass. I noticed my styling was broken and upon deeper inspection, I'm seeing that the svelte-token is being appended twice on any top-level selectors.  e.g.
```
<style type="text/scss">
 main {
   margin: 8px;
 }

 .content {
   color: blue;
   .test {
     display: none;
   }
 }
</style>
```

emits

```
main.svelte-u2gzuo.svelte-u2gzuo{margin:8px}
.content.svelte-u2gzuo.svelte-u2gzuo{color:blue}
.content.svelte-u2gzuo .test.svelte-u2gzuo{display:none}
```
into bundle.css (wrapped to make it easier to read).

Any idea what's causing this?

TIA,
Dave

**Comment by LukasHechenberger** [comment]
This is expected behavior, the CSS code is not broken. Works the same if not using SCSS:

[Svelte REPL](https://svelte.dev/repl/8caca299c13e4564aaf72c9e376f4600?version=3.16.7)

Please confirm and close this issue.

**Comment by dnmurray** [comment]
Thanks. Not sure why it was broken earlier, but it's working now.
