### ISSUE TITLE
Sass indented syntax

### ISSUE THREAD

**Issue by malikbenkirane** [ls-age/svelte-preprocess-sass#98]
https://github.com/ls-age/svelte-preprocess-sass/blob/1820e65ba0e083543810e5f273454e2f6a14528a/src/index.js#L6

According to [node-sass](https://github.com/sass/node-sass) this should be
```
sassOptions = {
  indentedSyntax: true,
}
```
As the default value is `false`

For example, this should compile
```sass
<style lang=“sass”>
$primary: red
button:
  color: $primary
</style>
```

Otherwise I didn't managed to work with neither sass nor scss syntax.

Should I PR ?

**Comment by monkape** [comment]
+1

Can't believe such a core feature is broken and no one cares.
